name = "conference-tracker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Replace YOUR_KV_ID with your actual KV namespace ID
kv_namespaces = [
  { binding = "CONFERENCES", id = "YOUR_KV_ID" }
]

# Environment variables will be set through wrangler secrets
# Run: wrangler secret put DISCORD_WEBHOOK_URL
# Run: wrangler secret put WIKICFP_BASE_URL

[triggers]
crons = ["0 */6 * * *"]

